- openssl/pbpal_resolv_and_connect_openssl.c
Free the certificate after using it.
> Fix memory leak

- openssl/pbpal_mutex.h
- openssl/pbpal_openssl.c
- openssl/pbpal_resolv_and_connect_openssl.c
- openssl/pubnub_internal.h
This PR handles two issues:
1. the TLS session resumption did not work reliably
2. OpenSSL was not correctly set-up when used in multi-threaded applications
> Improve OpenSSL integration

- .pubnub.yml
Add version, initial changelog and a few features.
> Update the Pubnub YAML file.

- core/pbgzip_decompress.c
- lib/miniz/miniz_tinfl.c
- openssl/pbpal_connect_openssl.c
Some logs added, some "upgraded" from printf()s to `PUBNUB_LOG_TRACE`s.
> Some logging improvements

- .pubnub.yml
- core/pubnub_timers.c
- core/pubnub_timers.h
- core/pubnub_version_internal.h
- core/test/pubnub_config.h
- freertos/pubnub_config.h
- microchip_harmony/pubnub_config.h
- openssl/pubnub_config.h
- posix/pubnub_config.h
- qt/pubnub_config.h
- qt/pubnub_qt.cpp
- qt/pubnub_qt.h
- windows/pubnub_config.h
Also use QTime for timer duration on Qt ("be more Qt-friendly").
> Introduce minimal transaction timer duration

- .pubnub.yml
- core/pubnub_version_internal.h
- cpp/pubnub_common.hpp
> Bring back set/get connection timeout

- .travis.yml
- core/pubnub_url_encode.h
fix: Encode = (equal) sign for filter expression
Encode = (equal) sign for filter expression
> Encode = (equal) sign for filter

- .github/workflows/release/versions.json
Fix `versions.json` file format, which cause issues during release.
> build: fix versions bump file

- .pubnub.yml
- CHANGELOG.md
- core/pbcc_subscribe_v2.c
- core/pubnub_version_internal.h
fix: filter-expr query param typo
filter-expr query param typo
> filter-expr param typo

- core/pbcc_advanced_history.c
- core/pubnub_ccore_pubsub.h
- core/pubnub_crypto.c
- core/pubnub_crypto.h
- core/pubnub_grant_token_api.c
- core/samples/pubnub_advanced_history_sample.c
- core/samples/pubnub_sync_grant_token_sample.c
- core/samples/pubnub_sync_revoke_token_sample.c
This PR fixes multiple memory safety and leak issues. Many are in the SDK itself, and some only affect sample code. See the individual commit messages for detailed information about what is getting fixed and how it was analyzed.
> Fix multiple memory safety and leak issues

- .pubnub.yml
- CHANGELOG.md
- core/pbcc_advanced_history.c
- core/pubnub_ccore_pubsub.h
- core/pubnub_crypto.c
- core/pubnub_crypto.h
- core/pubnub_grant_token_api.c
- core/pubnub_grant_token_api.h
- core/pubnub_url_encode.h
- core/pubnub_version_internal.h
- core/samples/pubnub_advanced_history_sample.c
- core/samples/pubnub_sync_grant_token_sample.c
- core/samples/pubnub_sync_revoke_token_sample.c
- cpp/pubnub_version_posix.cpp
- cpp/pubnub_version_windows.cpp
- cpp/samples/pubnub_sample_grant_token.cpp
- freertos/pubnub_version_freertos.c
- lib/sockets/pbpal_resolv_and_connect_sockets.c
- microchip_harmony/pubnub_version_harmony.c
- openssl/pubnub_version_openssl.c
- posix/pubnub_version_posix.c
- qt/pubnub_qt.cpp
- windows/pubnub_dns_system_servers.c
- windows/pubnub_version_windows.c
fix: Support system name servers in async DNS client
Support system name servers in async DNS client
fix: Fix multiple memory safety and leak issues
Fix multiple memory safety and leak issues
fix: Fix slash char encoding for pnsdk
Fix slash char encoding for pnsdk
> Consolidation of DNS resolve and memory related fixes

- .github/workflows/run_acceptance_tests.yml
fix(deploy): use proper deployment tools  
Use version-based deployment tools instead of specific branch.
> Use proper deployment tools version

- .github/CODEOWNERS
- .github/workflows/commands-handler.yml
- .github/workflows/composite/unit-test-framework/build-framework.sh
- .github/workflows/release.yml
- .github/workflows/run-tests.yml
- .github/workflows/run-validations.yml
build(workflow): fix syntax error in jon pre-condition
> Fix syntax error in jon pre-condition

- qt/pubnub_qt_gui_sample.cpp
- qt/pubnub_qt_gui_sample.h
fix: fix qt example
fix qt gui example
> fix qt example

- README.md
- unreal/PubNubModule/PubNubModule.Build.cs
- unreal/README.md
fix: fix readme about Windows build commands
Fix building path for Windows environment
fix: Unreal paths for Windows builds
Fix Unreal paths for Windows builds
> fix building process for Unreal Enigne

- .github/workflows/release/versions.json
build(regex): fix regular expression
> Fix regular expression

- .github/workflows/release/versions.json
build(release): fix backslash escaping
> Fix backslash escaping

- .pubnub.yml
- CHANGELOG.md
- core/pubnub_objects_api.c
- core/pubnub_version_internal.h
fix: removed additional null byte character
removed additional null byte character
> fix not needed null character

- .github/CODEOWNERS
- .github/workflows/commands-handler.yml
- .github/workflows/release.yml
- .github/workflows/run-tests.yml
- .github/workflows/run-validations.yml
build(workflow): fix organization runner group name
> Fix organization runner group name

- .github/workflows/run-tests.yml
- CMakeLists.txt
build(make): add `SDK_VERSION_SUFFIX` for partner id
Add `SDK_VERSION_SUFFIX` to extend `pnsdk` with additional information about implementation / partner.
> Add `SDK_VERSION_SUFFIX` for partner id

- core/pbcc_subscribe_v2.c
- core/pbcc_subscribe_v2.h
- core/pubnub_subscribe_event_engine.c
- core/pubnub_subscribe_v2.c
- core/pubnub_subscribe_v2.h
- qt/pubnub_qt.cpp
- qt/pubnub_qt.h
> Revert "Add timetoken parameter for `pubnub_subscribe_v2`"

- .pubnub.yml
- CHANGELOG.md
- core/pubnub_version_internal.h
- freertos/pbpal_mutex.h
refactor(mutex): use recursive `mutex` for FreeRTOS
Use recursive semaphore for `mutex` lock and unlock in `pbpal_mutex.h`.
> xSemaphoreCreateRecursiveMutex
