- openssl/pbpal_openssl.c
When an openssl transaction was cancelled it was not possible to start a new transaction.
It would perhaps be a good idea to write a test for this, but the tests are currently failing on my system because quota are exceeded with the used account.
> Cannot start new openssl transaction after previous transaction was cancelled

- openssl/pbpal_openssl.c
- openssl/pbpal_resolv_and_connect_openssl.c
- openssl/pubnub_internal.h
Use timeout on openssl connection to ensure BIO_read does not block infinitely
> OpenSSL: Set timeout

- core/pubnub_ssl.c
- openssl/posix.mk
- openssl/pubnub_config.h
- `core/pubnub_ssl.c` was not compiling
- we should be able to set the buffer sizes from outside the project
> Minor fixes/improvements

- openssl/pbpal_add_system_certs_windows.c
- The SSL_CTX member of pubnub_pal is called ctx instead of sslCtx.
- Semicolon was needed
- wincrypt needs windows.h
> Fixed reference to SSL_CTX member of pubnub_pal

- cpp/pubnub_futres_cpp11.cpp
- cpp/pubnub_futres_posix.cpp
- cpp/pubnub_futres_windows.cpp
Neglecting to do so can cause other threads to crash; for example, if they call pubnub::context::cancel() while no transactions are in progress on that context.
> pubnub::futres must unregister its callback upon destruction.

- core/pubnub_ccore.c
- cpp/posix.mk
This happens when you try to publish to a channel you don't have
access rights (PAM) to. Result is then returned as a JSON object,
rather than an array. Now we handle it and report a "publishing error",
instead of a "format error".
> Fixed parsing of publish response "forbidden".

- qt/pubnub_qt.cpp
Sometimes it is useful to modify the default timeout duration which is 10s by default.
The headers appeared to offer the functionality, but it was missing.  This PR offers an implementation.
Sample usage: 
```
pubnub_qt r;
r.set_transaction_timeout(5000); // OK; This will return 0 and sets the transaction
int timeout_s = r.transaction_timeout_get(); // Returns 5000;
r.publish(...); 
// ... 
r.set_transaction_timeout(-20); // Not OK; This will return -1 and keep the previous transaction timeout.
```
> Add set_transaction_timeout and transaction_timeout_get Qt implementations

- core/pubnub_ccore.c
Hey guys, 
I had issues using pubnub_history_ex. Setting the arguments 'stringtoken' and 'reverse' to true had no effect. After investigating I found out that apparently the [PubNub REST API for fetching the history](https://www.pubnub.com/docs/pubnub-rest-api-documentation#history) wants to have only true and false as Boolean values, in the code those values were encoded as 1 and 0 however. Changing the macros for those two arguments from APPEND_URL_PARAM_TRIBOOL_M to APPEND_URL_PARAM_BOOL_M fixed the issue.
> Fetch history not accepting 0 or 1 as Boolean values

- .pubnub.yml
- core/pbcc_objects_api.c
- core/pbcc_objects_api.h
- core/pbcc_subscribe_v2.c
- core/pubnub_api_types.h
- core/pubnub_netcore.c
- core/pubnub_objects_api.c
- core/pubnub_objects_api.h
- core/pubnub_pubsubapi.h
- core/pubnub_subscribe_v2_message.h
- core/pubnub_version_internal.h
- cpp/pubnub_common.hpp
- qt/pubnub_qt.cpp
- qt/pubnub_qt.h
Complete and tested support for Objects API.
Code has been there for a while, but incomplete and not fully tested (or debugged). Also, it had the "old" names of transactions.
> Objects API

- .pubnub.yml
- core/pbpal_ntf_callback_handle_timer_list.c
- skip attempt to remove timer from list if the list is empty
- this can happen while handling multiple queued timeouts
> Fix assertion failure when retrying DNS query

- .pubnub.yml
- core/pbpal_ntf_callback_handle_timer_list.c
- core/pubnub_alloc_std.c
- core/pubnub_core_unit_test.c
- core/pubnub_netcore.c
- core/pubnub_netcore.h
- core/pubnub_proxy_unit_test.c
- core/pubnub_version_internal.h
Bottom line is that `pbnc_stop()` was not designed to handle
anything itself, only to "setup the stage" for the FSM to
handle things.  Unfortunately, in these two scenarios, some
handling had "slipped in".
> Fix handling of DNS retries and stale HTTP kept alive

- .pubnub.yml
- core/pubnub_version_internal.h
Dynamically allocate memory for `uuid` in `pubnub_set_uuid` function.
> PubNub SDK 2.12.5 Release

- lib/sockets/pbpal_resolv_and_connect_sockets.c
- windows/pubnub_dns_system_servers.c
This is an alternative to #120.
The name server is chosen with the following precedence:
1. The server specified with `pubnub_dns_set_primary_server_ipv4()` (assumes `PUBNUB_SET_DNS_SERVERS` is set, which is the default)
2. The server specified with `pubnub_dns_set_secondary_server_ipv4()` (assumes `PUBNUB_SET_DNS_SERVERS` is set, which is the default)
3. The server configured by the system (e.g. DHCP or manually)
4. The hardcoded default server (usually `8.8.8.8`)
If any step fails to find a server, it will try the next in the precedence list. Step 4 always succeeds.
When `PUBNUB_SET_DNS_SERVERS` is _not_ set, the name server configured on the system is always chosen first.
This patch also fixes a minor memory leak in the Windows-specific name server lookup function when an error occurs.
> Support system name servers in async DNS client

- .pubnub.yml
- CHANGELOG.md
- core/pubnub_ccore.c
- core/pubnub_ccore_pubsub.c
- core/pubnub_core_unit_test.c
- core/pubnub_subscribe_with_state.c
- core/pubnub_version_internal.h
- lib/sockets/pbpal_resolv_and_connect_sockets.c
fix: Removed extra parenthesis in get_dns_ip function code
Removed extra parenthesis in get_dns_ip function code
fix: Added uuid query param to history, set/get state, wherenow, channel-group operations
Added uuid query param to history, set/get state, wherenow, channel-group operations
> Missing UUID query param

- .pubnub.yml
- CHANGELOG.md
- core/pubnub_grant_token_api.c
- core/pubnub_grant_token_api.h
- core/pubnub_version_internal.h
- cpp/pubnub_common.hpp
- lib/pb_strncasecmp.c
- openssl/pbaes256.c
fix: fix memory leak in cpp `parse_token` method
fix: fix buffer overflow in core `pubnub_parse_token` function for some cases
fix: fix buffer overflow in core `pubnub_encrypt` function for randomized initial vector
> Fix token memory leak

- core/pubnub_crypto.c
- openssl/pbpal_openssl.c
`ERR_load_BIO_strings()` is deprecated in OpenSSL 3.0. Low-level encoding primitives are also deprecated. `EVP_EncodeBlock()` is available in all currently supported OpenSSL releases.
> fix build with OpenSSL 3.0

- .pubnub.yml
- CHANGELOG.md
- core/pubnub_crypto.c
- core/pubnub_version_internal.h
- core/samples/pubnub_encrypt_decrypt_iv_sample.c
fix: Fixed buffer underflow in encryption
Improved accuracy of the base64 encoding size what fixes buffer underflow in encryption module
fix: Fixed undefined behaviours in `pubnub_encrypt_decrypt_iv_sample.c`
Fixed undefined behaviours in `pubnub_encrypt_decrypt_iv_sample.c` by including some additional checks and variable initialisations
refactor: Made same base for encrypt functions
Made same base for encrypt functions what makes codes easier to understand and maintain
> Fix some issues with encryption

- .pubnub.yml
- CHANGELOG.md
- core/pubnub_grant_token_api.c
- core/pubnub_version_internal.h
- cpp/pubnub_common.hpp
fix: wrong pointer management
Fixed wrong pointer reallocation in string concatenation
fix: token parsing allocation counter
Fixed allocation counter that was not taking to the account recursed allocations
> fix crashing when parsing access tokens

- .pubnub.yml
- CHANGELOG.md
- core/Makefile
- core/pubnub_core_unit_test.c
- core/pubnub_grant_token_api.c
- core/pubnub_grant_token_api.h
- core/pubnub_version_internal.h
- lib/base64/pbbase64.c
fix: fix crashing parsing token for not valid values
Fixed crashing parsing token for not valid values by logging an error and returning `NULL`.
> fix crashing parsing token for not valid values

- .pubnub.yml
- CHANGELOG.md
- core/pubnub_grant_token_api.c
- core/pubnub_version_internal.h
fix: MSVC compilation error
Fixed compilation error for MSVC in `pubnub_parse_token` function.
> fix MSVC compiler for parse_token

- .gitignore
- .pubnub.yml
- CHANGELOG.md
- core/Makefile
- core/pbcc_subscribe_v2.c
- core/pubnub_subscribe_v2_message.h
- core/pubnub_subscribe_v2_unit_test.c
- core/pubnub_version_internal.h
- core/samples/metadata.c
- core/test/pubnub_test_mocks.c
- core/test/pubnub_test_mocks.h
- cpp/pubnub_v2_message.hpp
feat: add `publisher` field in subscribe v2 message
Add `publisher` field into `pubnub_v2_message`
fix: fix `flags` and `region` values in subscribe v2 message
Fixed `flags` and `region` values that always equaled `0`
> add `publisher` field in subscribe v2 message + fix `region` and `flags` fields

- .pubnub.yml
- CHANGELOG.md
- core/pubnub_version_internal.h
- qt/README.md
- qt/pubnub.pro
- qt/pubnub_gui.pro
- qt/pubnub_qt.cpp
fix: move `pubnub_qt` into QT main thread
Move `pubnub_qt` into QT main thread by default to be sure that timers will be run in it
feat: add `PUBNUB_QT_MOVE_TO_THREAD` flag as default
Add the `PUBNUB_QT_MOVE_TO_THREAD` flag as default to give users the opportunity to manage threads by themselves.
> move `pubnub_qt` into main thread

- .pubnub.yml
- CHANGELOG.md
- core/pubnub_coreapi_ex.c
- core/pubnub_version_internal.h
- qt/pubnub_gui.pro
- qt/pubnub_qt.cpp
- qt/pubnub_qt.h
fix: Provide missing `publish()` function overload for QT wrapper
Provide missing `publish()` function overload for QT wrapper that allows set publish related options
> provide missing `publish()` function overload for qt

- .pubnub.yml
- CHANGELOG.md
- core/pubnub_alloc_static.c
- core/pubnub_alloc_std.c
- core/pubnub_core_unit_test.c
- core/pubnub_version_internal.h
fix: fix `pubnub_free()` function on not initialised PubNub
Fix `pubnub_free()` function on not initialised PubNub that can cause exceptions/undefined behaviours
> fix free on not initialised PubNub

- CMakeLists.txt
I tested the new CMake branch. The build works great but I ran into some issues when integrating PubNub into an external CMake project
Demo project is set up as shown
CMake build fails on missing symbols and missing headers
PR includes fixes for symbols and uses the preferred target based headers `target_include_directories`. To do this i moved the source file list creation above the target `add_library` and moved the header includes below the target creation.
> CMake External Project Fixes

- CMakeLists.txt
- lib/pb_extern.h
Builds on top of #173 and so should not merge before 173.
Adds CPP samples and supports sync and callback apis
Adds an options overview so its easier to see which features are configured
TODO:
- Support tests
- Fix segfault
> CMake CPP Support

- .github/workflows/release/versions.json
- .pubnub.yml
- CHANGELOG.md
- CMakeLists.txt
- core/pbcc_crypto_legacy.c
fix: fix too small amount of memory allocated for aes cbc algorithm in some cases.  
Fix too small amount of memory allocated for aes cbc algorithm in some cases.  
build: add possibility to include address sanitizer in build via CMake. 
Add possibility to include address sanitizer in build via CMake.
> fix some crypto issues

- CMakeLists.txt
Previous build didn't work when OpenSSL was enabled.
> Fix CMake commands to build correctly for Windows.

- .github/workflows/release/versions.json
- .pubnub.yml
- CHANGELOG.md
- CMakeLists.txt
- core/pbcc_actions_api.c
- core/pbcc_actions_api.h
- core/pubnub_actions_api.c
- core/pubnub_actions_api.h
- core/pubnub_version_internal.h
feat: possibility to use string in actions API
Added possibility to use strings in actions API
refactor: `pubnub_action_type` deprecated
`pubnub_action_type` enum has been deprecated
> strings in objects API

- .pubnub.yml
- CHANGELOG.md
- CMakeLists.txt
- core/pubnub_version_internal.h
fix: fix `cmake` build for not ESP32 builds
Fixed `cmake` build for not ESP32 builds
> fix cmake file for not ESP32 builds

- .pubnub.yml
- CHANGELOG.md
- core/Makefile
- core/pbcc_crypto.c
- core/pbcc_crypto.h
- core/pbcc_subscribe_v2.c
- core/pubnub_ccore_pubsub.c
- core/pubnub_crypto_unit_tests.c
- core/pubnub_version_internal.h
fix: added missing subscribe v2 crypto implementation
Added missing subscribe v2 crypto implementation
> add missing subscribe v2 crypto implementation

- .pubnub.yml
- CHANGELOG.md
- CMakeLists.txt
- core/c99/stdbool.h
- core/pbcc_objects_api.c
- core/pbcc_objects_api.h
- core/pubnub_objects_api.c
- core/pubnub_objects_api.h
- core/pubnub_version_internal.h
- core/samples/pubnub_objects_api_sample.c
- posix/pubnub_version_posix.c
- windows/pubnub_version_windows.c
feat: added `filter` and `sort` parameters to be closer to the other SDKs with object API. 
added `filter` and `sort` parameters to be closer to the other SDKs with object API. 
feat: configurable `bool` type.
configurable `bool` type.
fix: missing features needed for grant token API in CMakeLIsts.txt
missing features needed for grant token API in CMakeLIsts.txt
> few tweaks for objects api

- .pubnub.yml
- CHANGELOG.md
- core/pbcc_fetch_history.c
- core/pubnub_version_internal.h
- core/samples/pubnub_fetch_history_sample.c
fix(history): fix query parameter values
Fix query values for boolean flags for history endpoint (`include meta`, `include uuid`, `include message type` and `reverse`).
> Fix history query parameter values

- .pubnub.yml
- CHANGELOG.md
- CMakeLists.txt
- core/pubnub_version_internal.h
fix: fix custom `bool` type for CMake builds
fixed custom `bool` type for CMake builds
> fix custom `bool` type for CMake builds

- .pubnub.yml
- CHANGELOG.md
- core/pubnub_ccore_pubsub.c
- core/pubnub_ccore_pubsub.h
- core/pubnub_coreapi_ex.c
- core/pubnub_coreapi_ex.h
- core/pubnub_objects_api.c
- core/pubnub_pubsubapi.c
- core/pubnub_version_internal.h
- core/samples/pubnub_publish_via_post_sample.c
fix(publish): add missing `ttl` parameter
Add the missing `ttl` parameter to the `pubnub_publish_options` for extended `publish` configuration.
> Add missing `ttl` parameter

- .pubnub.yml
- CHANGELOG.md
- core/pbcc_advanced_history.c
- core/pbcc_advanced_history.h
- core/pubnub_advanced_history.c
- core/pubnub_advanced_history.h
- core/pubnub_api_types.h
- core/pubnub_netcore.c
- core/pubnub_version_internal.h
- core/samples/pubnub_advanced_history_sample.c
- qt/pubnub_qt.cpp
feat(history): add delete messages API
Add `delete message` API support to the advanced history module.
> Add delete messages API

- .pubnub.yml
- CHANGELOG.md
- core/pubnub_objects_api.c
- core/pubnub_objects_api.h
- core/pubnub_version_internal.h
- core/samples/pubnub_objects_api_sample.c
- make/common/targets_app.mk
feat(app-context): add `status` and `types` support
Add `status` and `type` support for channel and uuid metadata objects state update API.
> Add `status` and `types` support

- core/pbcc_subscribe_v2.c
- core/pbcc_subscribe_v2.h
- core/pubnub_subscribe_event_engine.c
- core/pubnub_subscribe_v2.c
- core/pubnub_subscribe_v2.h
- qt/pubnub_qt.cpp
- qt/pubnub_qt.h
feat(subscribe): add timetoken parameter for `pubnub_subscribe_v2`
Add the ability to set `timetoken` (for message catchup) in `pubnub_subscribe_v2_options` which is used with `pubnub_subscribe_v2`.
fix(subscription): fix memory issues with freed subscriptions
Fix issue which was source of segmentation fault when tried to access memory after it has been freed.
> Add timetoken parameter for `pubnub_subscribe_v2`

- .pubnub.yml
- CHANGELOG.md
- core/pbcc_objects_api.c
- core/pubnub_version_internal.h
fix(objects): fix objects api to accept `limit` with value 100
Fix the issue that there was an assertion when using App Context functions with `limit` set to 100
> Fix objects api to accept limit 100

- core/pbcc_subscribe_event_listener.c
- core/pbcc_subscribe_event_listener.h
- core/pubnub_subscribe_event_listener.c
- core/pubnub_subscribe_event_listener.h
- core/pubnub_subscribe_event_listener_types.h
- core/samples/pubnub_api_enforcement_sample.c
- core/samples/subscribe_event_engine_sample.c
feat: introduce `void*` parameter for user data in listeners
Introduce `void*` parameter for user data in listeners to let callbacks keep context on demand.
> introduce `void*` parameter for user data in listeners

- .pubnub.yml
- CHANGELOG.md
- core/pbcc_set_state.c
- core/pubnub_version_internal.h
fix: Fixed wrong string copy if multiple channels(groups) are provided for `pubnub_set_state`
Fixed wrong string copy if multiple channels(groups) are provided for `pubnub_set_state`. Note that using `memcpy` instead of `strncpy` is used intentionally because of the ESP support. 
fix: Fixed crash when double comma is provided to `pubnub_set_state` as a channels(groups).
Fixed crash when double comma is provided to `pubnub_set_state` as a channels(groups). 
fix: Fixed wrong check if the reallocation is required in `pubnub_set_state`.
Fixed wrong check if the reallocation is required in `pubnub_set_state`.
fix: Removed additional allocation of memory for temporary data.
Removed additional allocation of memory for temporary data.
fix: Changed the amount of bytes allocated based on the …
> fix Address Sanitiser reports in `pubnub_set_state` function

- .pubnub.yml
- CHANGELOG.md
- core/pubnub_version_internal.h
- mbedtls/pbpal_mbedtls.c
fix: Fixes memory leak when calling pubnub_free on an initialized PubNub object
Fixed memory leak when calling pubnub_free on an initialized PubNub object
fix: Fixes socket leak when calling pubnub_free on a PubNub object with an open connection
Fixed socket leak when calling pubnub_free on a PubNub object with an open connection
fix: Fixes socket leak when publishing using a context with use_http_keep_alive = 0
Fixed socket leak when publishing using a context with use_http_keep_alive = 0
fix: Fixes crash due to double-free when calling pubnub_free after pbpal_handle_socket_condition encounters a socket error
Fixed crash due to double-free when calling pubnub_free after pbpal_handle_socket_condition encounters a socket error
Thanks to @blake-spangenberg for fixing issues mentioned above! …
> pbpal_mbedtls: Fix socket and memory leaks

- .pubnub.yml
- CHANGELOG.md
- core/pbcc_objects_api.c
- core/pubnub_ccore.c
- core/pubnub_core_unit_test.c
- core/pubnub_subscribe_with_state.c
- core/pubnub_url_encode.h
- core/pubnub_version_internal.h
fix(general): Fix UTF8 characters not working in some end points.
Fix bug that UTF8 characters used in some end points were breaking the request format.
> Fix UTF8 characters not working in some end points.
